Fix the verify-pod-security-standards target which was silently failing
There were multiple problems:

1. The INSTALL_OPTIONS were not being used
   So for charts with required options the `helm template` command was failing,
   but the make target exited with 0. E.g. in firefly

```
$ make verify-pod-security-standards
...
Error: execution error at (firefly/templates/NOTES.txt:8:4): please supply the clientID for your Venafi TLS Protect Cloud service account, by setting the Helm value `deployment.venafiClientID: <CLIENT_ID>` or by supplying the command line option `--set deployment.venafiClientID=<CLIENT_ID>`.

Use --debug flag to render out invalid YAML

Applying 0 policy rule(s) to 0 resource(s)...

pass: 0, fail: 0, warn: 0, error: 0, skip: 0

$ echo $?
0
```

2. `kyverno apply` was not reading the policy from the process substitution.
   The command was exiting with 0 as follows:

```
$ make verify-pod-security-standards
...
Applying 0 policy rule(s) to 16 resource(s)...

pass: 0, fail: 0, warn: 0, error: 0, skip: 0

$ echo $?
0
```

3. There was no way to provide exceptions, for when the deployment contains
expected violations.

Signed-off-by: Richard Wall <richard.wall@venafi.com>